export const IMMERSIVE_WORKSPACE_SURFACE_OVERLAY_Z_CLASS = 'z-[100005]';
export const IMMERSIVE_WORKSPACE_SURFACE_CONTENT_Z_CLASS = 'z-[100010]';
export const IMMERSIVE_WORKSPACE_ALERT_OVERLAY_Z_CLASS = 'z-[100020]';
export const IMMERSIVE_WORKSPACE_ALERT_CONTENT_Z_CLASS = 'z-[100025]';
