export const WORKSPACE_CHOOSE_DIRECTORY_CHANNEL = 'workspace:chooseDirectory' as const;
export const WORKSPACE_LIST_MEMORY_SPACES_CHANNEL = 'workspace:listMemorySpaces' as const;
export const WORKSPACE_INITIALIZE_CHANNEL = 'workspace:initialize' as const;
export const WORKSPACE_OPEN_CHANNEL = 'workspace:open' as const;
export const WORKSPACE_OPEN_MEMORY_SPACE_CHANNEL = 'workspace:openMemorySpace' as const;
export const WORKSPACE_REMOVE_MEMORY_SPACE_CHANNEL = 'workspace:removeMemorySpace' as const;
export const WORKSPACE_UPDATE_MEMORY_SPACE_TITLE_CHANNEL =
  'workspace:updateMemorySpaceTitle' as const;
export const WORKSPACE_CLOSE_CHANNEL = 'workspace:close' as const;
export const WORKSPACE_READ_WORKSPACE_SNAPSHOT_CHANNEL = 'workspace:readWorkspaceSnapshot' as const;
export const WORKSPACE_CREATE_MEMORY_CHANNEL = 'workspace:createMemory' as const;
export const WORKSPACE_DELETE_MEMORY_CHANNEL = 'workspace:deleteMemory' as const;
export const WORKSPACE_RESTORE_DELETED_MEMORY_CHANNEL = 'workspace:restoreDeletedMemory' as const;
export const WORKSPACE_DELETE_SEGMENT_CHANNEL = 'workspace:deleteSegment' as const;
export const WORKSPACE_RESTORE_DELETED_SEGMENT_CHANNEL = 'workspace:restoreDeletedSegment' as const;
export const WORKSPACE_DELETE_SEGMENT_SUPPLEMENT_CHANNEL =
  'workspace:deleteSegmentSupplement' as const;
export const WORKSPACE_RESTORE_DELETED_SEGMENT_SUPPLEMENT_CHANNEL =
  'workspace:restoreDeletedSegmentSupplement' as const;
export const WORKSPACE_READ_MEMORY_DETAIL_CHANNEL = 'workspace:readMemoryDetail' as const;
export const WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_CHANNEL =
  'workspace:readFinalizedAudioSegment' as const;
export const WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_SUPPLEMENT_CHANNEL =
  'workspace:readFinalizedAudioSegmentSupplement' as const;
export const WORKSPACE_CREATE_RECORDING_DRAFT_CHANNEL = 'workspace:createRecordingDraft' as const;
export const WORKSPACE_CREATE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL =
  'workspace:createSegmentSupplementRecordingDraft' as const;
export const WORKSPACE_READ_RECORDING_DRAFT_AUDIO_CHANNEL =
  'workspace:readRecordingDraftAudio' as const;
export const WORKSPACE_APPEND_RECORDING_AUDIO_CHUNK_CHANNEL =
  'workspace:appendRecordingAudioChunk' as const;
export const WORKSPACE_APPEND_SEGMENT_SUPPLEMENT_RECORDING_AUDIO_CHUNK_CHANNEL =
  'workspace:appendSegmentSupplementRecordingAudioChunk' as const;
export const WORKSPACE_CLONE_RECORDING_DRAFT_PREFIX_CHANNEL =
  'workspace:cloneRecordingDraftPrefix' as const;
export const WORKSPACE_FINALIZE_RECORDING_DRAFT_CHANNEL =
  'workspace:finalizeRecordingDraft' as const;
export const WORKSPACE_FINALIZE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL =
  'workspace:finalizeSegmentSupplementRecordingDraft' as const;
export const WORKSPACE_DISCARD_RECORDING_DRAFT_CHANNEL = 'workspace:discardRecordingDraft' as const;
export const WORKSPACE_DISCARD_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL =
  'workspace:discardSegmentSupplementRecordingDraft' as const;
export const WORKSPACE_UPDATE_MEMORY_TITLE_CHANNEL = 'workspace:updateMemoryTitle' as const;
export const WORKSPACE_UPDATE_SEGMENT_TITLE_CHANNEL = 'workspace:updateSegmentTitle' as const;
export const WORKSPACE_UPDATE_SEGMENT_SUPPLEMENT_TITLE_CHANNEL =
  'workspace:updateSegmentSupplementTitle' as const;
export const WORKSPACE_SAVE_TRANSCRIPT_CHANNEL = 'workspace:saveTranscript' as const;
export const WORKSPACE_SAVE_SEGMENT_SUPPLEMENT_TRANSCRIPT_CHANNEL =
  'workspace:saveSegmentSupplementTranscript' as const;
export const WORKSPACE_BEGIN_MICROPHONE_INTENT_CHANNEL = 'workspace:beginMicrophoneIntent' as const;
export const WORKSPACE_CLEAR_MICROPHONE_INTENT_CHANNEL = 'workspace:clearMicrophoneIntent' as const;
export const WORKSPACE_START_RECORDING_TRANSCRIPTION_CHANNEL =
  'workspace:startRecordingTranscription' as const;
export const WORKSPACE_SEND_RECORDING_TRANSCRIPTION_AUDIO_CHANNEL =
  'workspace:sendRecordingTranscriptionAudio' as const;
export const WORKSPACE_FINISH_RECORDING_TRANSCRIPTION_CHANNEL =
  'workspace:finishRecordingTranscription' as const;
export const WORKSPACE_CLOSE_RECORDING_TRANSCRIPTION_CHANNEL =
  'workspace:closeRecordingTranscription' as const;
export const WORKSPACE_RECORDING_TRANSCRIPTION_EVENT_CHANNEL =
  'workspace:recordingTranscriptionEvent' as const;

export const WORKSPACE_IPC_CHANNELS = [
  WORKSPACE_CHOOSE_DIRECTORY_CHANNEL,
  WORKSPACE_LIST_MEMORY_SPACES_CHANNEL,
  WORKSPACE_INITIALIZE_CHANNEL,
  WORKSPACE_OPEN_CHANNEL,
  WORKSPACE_OPEN_MEMORY_SPACE_CHANNEL,
  WORKSPACE_REMOVE_MEMORY_SPACE_CHANNEL,
  WORKSPACE_UPDATE_MEMORY_SPACE_TITLE_CHANNEL,
  WORKSPACE_CLOSE_CHANNEL,
  WORKSPACE_READ_WORKSPACE_SNAPSHOT_CHANNEL,
  WORKSPACE_CREATE_MEMORY_CHANNEL,
  WORKSPACE_DELETE_MEMORY_CHANNEL,
  WORKSPACE_RESTORE_DELETED_MEMORY_CHANNEL,
  WORKSPACE_DELETE_SEGMENT_CHANNEL,
  WORKSPACE_RESTORE_DELETED_SEGMENT_CHANNEL,
  WORKSPACE_DELETE_SEGMENT_SUPPLEMENT_CHANNEL,
  WORKSPACE_RESTORE_DELETED_SEGMENT_SUPPLEMENT_CHANNEL,
  WORKSPACE_READ_MEMORY_DETAIL_CHANNEL,
  WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_CHANNEL,
  WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_SUPPLEMENT_CHANNEL,
  WORKSPACE_CREATE_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_CREATE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_READ_RECORDING_DRAFT_AUDIO_CHANNEL,
  WORKSPACE_APPEND_RECORDING_AUDIO_CHUNK_CHANNEL,
  WORKSPACE_APPEND_SEGMENT_SUPPLEMENT_RECORDING_AUDIO_CHUNK_CHANNEL,
  WORKSPACE_CLONE_RECORDING_DRAFT_PREFIX_CHANNEL,
  WORKSPACE_FINALIZE_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_FINALIZE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_DISCARD_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_DISCARD_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_UPDATE_MEMORY_TITLE_CHANNEL,
  WORKSPACE_UPDATE_SEGMENT_TITLE_CHANNEL,
  WORKSPACE_UPDATE_SEGMENT_SUPPLEMENT_TITLE_CHANNEL,
  WORKSPACE_SAVE_TRANSCRIPT_CHANNEL,
  WORKSPACE_SAVE_SEGMENT_SUPPLEMENT_TRANSCRIPT_CHANNEL,
  WORKSPACE_BEGIN_MICROPHONE_INTENT_CHANNEL,
  WORKSPACE_CLEAR_MICROPHONE_INTENT_CHANNEL,
  WORKSPACE_START_RECORDING_TRANSCRIPTION_CHANNEL,
  WORKSPACE_SEND_RECORDING_TRANSCRIPTION_AUDIO_CHANNEL,
  WORKSPACE_FINISH_RECORDING_TRANSCRIPTION_CHANNEL,
  WORKSPACE_CLOSE_RECORDING_TRANSCRIPTION_CHANNEL,
] as const;

export type WorkspaceIpcChannel = (typeof WORKSPACE_IPC_CHANNELS)[number];

export const WORKSPACE_RENDERER_EVENT_CHANNELS = [
  WORKSPACE_RECORDING_TRANSCRIPTION_EVENT_CHANNEL,
] as const;

export type WorkspaceRendererEventChannel = (typeof WORKSPACE_RENDERER_EVENT_CHANNELS)[number];
