export const WORKSPACE_CHOOSE_DIRECTORY_CHANNEL = 'workspace:chooseDirectory' as const;
export const WORKSPACE_LIST_MEMORY_SPACES_CHANNEL = 'workspace:listMemorySpaces' as const;
export const WORKSPACE_READ_SYSTEM_DRAFT_WORKSPACE_CHANNEL =
  'workspace:readSystemDraftWorkspace' as const;
export const WORKSPACE_OPEN_SYSTEM_DRAFT_WORKSPACE_CHANNEL =
  'workspace:openSystemDraftWorkspace' as const;
export const WORKSPACE_READ_RECENT_EXPRESSIONS_CHANNEL = 'workspace:readRecentExpressions' as const;
export const WORKSPACE_INITIALIZE_CHANNEL = 'workspace:initialize' as const;
export const WORKSPACE_OPEN_CHANNEL = 'workspace:open' as const;
export const WORKSPACE_OPEN_MEMORY_SPACE_CHANNEL = 'workspace:openMemorySpace' as const;
export const WORKSPACE_REMOVE_MEMORY_SPACE_CHANNEL = 'workspace:removeMemorySpace' as const;
export const WORKSPACE_UPDATE_MEMORY_SPACE_TITLE_CHANNEL =
  'workspace:updateMemorySpaceTitle' as const;
export const WORKSPACE_CLOSE_CHANNEL = 'workspace:close' as const;
export const WORKSPACE_READ_WORKSPACE_SNAPSHOT_CHANNEL = 'workspace:readWorkspaceSnapshot' as const;
export const WORKSPACE_CREATE_MEMORY_CHANNEL = 'workspace:createMemory' as const;
export const WORKSPACE_DELETE_MEMORY_CHANNEL = 'workspace:deleteMemory' as const;
export const WORKSPACE_RESTORE_DELETED_MEMORY_CHANNEL = 'workspace:restoreDeletedMemory' as const;
export const WORKSPACE_RESET_MEMORY_COVER_CHANNEL = 'workspace:resetMemoryCover' as const;
export const WORKSPACE_RESTORE_MEMORY_COVER_CHANNEL = 'workspace:restoreMemoryCover' as const;
export const WORKSPACE_SWITCH_MEMORY_DEFAULT_COVER_CHANNEL =
  'workspace:switchMemoryDefaultCover' as const;
export const WORKSPACE_RESET_SEGMENT_COVER_CHANNEL = 'workspace:resetSegmentCover' as const;
export const WORKSPACE_RESTORE_SEGMENT_COVER_CHANNEL = 'workspace:restoreSegmentCover' as const;
export const WORKSPACE_SWITCH_SEGMENT_DEFAULT_COVER_CHANNEL =
  'workspace:switchSegmentDefaultCover' as const;
export const WORKSPACE_DELETE_SEGMENT_CHANNEL = 'workspace:deleteSegment' as const;
export const WORKSPACE_RESTORE_DELETED_SEGMENT_CHANNEL = 'workspace:restoreDeletedSegment' as const;
export const WORKSPACE_DELETE_SEGMENT_SUPPLEMENT_CHANNEL =
  'workspace:deleteSegmentSupplement' as const;
export const WORKSPACE_RESTORE_DELETED_SEGMENT_SUPPLEMENT_CHANNEL =
  'workspace:restoreDeletedSegmentSupplement' as const;
export const WORKSPACE_DELETE_WIDGET_CHANNEL = 'workspace:deleteWidget' as const;
export const WORKSPACE_RESTORE_DELETED_WIDGET_CHANNEL = 'workspace:restoreDeletedWidget' as const;
export const WORKSPACE_READ_MEMORY_DETAIL_CHANNEL = 'workspace:readMemoryDetail' as const;
export const WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_CHANNEL =
  'workspace:readFinalizedAudioSegment' as const;
export const WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_SUPPLEMENT_CHANNEL =
  'workspace:readFinalizedAudioSegmentSupplement' as const;
export const WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_AUDIO_CHANNEL =
  'workspace:readFinalizedAudioSegmentAudio' as const;
export const WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_SUPPLEMENT_AUDIO_CHANNEL =
  'workspace:readFinalizedAudioSegmentSupplementAudio' as const;
export const WORKSPACE_READ_EXPRESSION_PLAYBACK_AUDIO_CHANNEL =
  'workspace:readExpressionPlaybackAudio' as const;
export const WORKSPACE_CREATE_RECORDING_DRAFT_CHANNEL = 'workspace:createRecordingDraft' as const;
export const WORKSPACE_CREATE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL =
  'workspace:createSegmentSupplementRecordingDraft' as const;
export const WORKSPACE_CREATE_NOTE_SEGMENT_DRAFT_CHANNEL =
  'workspace:createNoteSegmentDraft' as const;
export const WORKSPACE_CREATE_SEGMENT_SUPPLEMENT_NOTE_DRAFT_CHANNEL =
  'workspace:createSegmentSupplementNoteDraft' as const;
export const WORKSPACE_WRITE_NOTE_SEGMENT_DRAFT_BODY_CHANNEL =
  'workspace:writeNoteSegmentDraftBody' as const;
export const WORKSPACE_WRITE_SEGMENT_SUPPLEMENT_NOTE_DRAFT_BODY_CHANNEL =
  'workspace:writeSegmentSupplementNoteDraftBody' as const;
export const WORKSPACE_FINALIZE_NOTE_SEGMENT_DRAFT_CHANNEL =
  'workspace:finalizeNoteSegmentDraft' as const;
export const WORKSPACE_FINALIZE_SEGMENT_SUPPLEMENT_NOTE_DRAFT_CHANNEL =
  'workspace:finalizeSegmentSupplementNoteDraft' as const;
export const WORKSPACE_READ_SEGMENT_CONTENT_CHANNEL = 'workspace:readSegmentContent' as const;
export const WORKSPACE_WRITE_SEGMENT_CONTENT_CHANNEL = 'workspace:writeSegmentContent' as const;
export const WORKSPACE_READ_SEGMENT_SUPPLEMENT_CONTENT_CHANNEL =
  'workspace:readSegmentSupplementContent' as const;
export const WORKSPACE_READ_SEGMENT_SPEECH_AUDIO_CHANNEL =
  'workspace:readSegmentSpeechAudio' as const;
export const WORKSPACE_READ_SEGMENT_SUPPLEMENT_SPEECH_AUDIO_CHANNEL =
  'workspace:readSegmentSupplementSpeechAudio' as const;
export const WORKSPACE_WRITE_SEGMENT_SUPPLEMENT_CONTENT_CHANNEL =
  'workspace:writeSegmentSupplementContent' as const;
export const WORKSPACE_SAVE_SEGMENT_ATTACHMENT_CHANNEL = 'workspace:saveSegmentAttachment' as const;
export const WORKSPACE_LIST_SEGMENT_ATTACHMENTS_CHANNEL =
  'workspace:listSegmentAttachments' as const;
export const WORKSPACE_SAVE_SEGMENT_SUPPLEMENT_ATTACHMENT_CHANNEL =
  'workspace:saveSegmentSupplementAttachment' as const;
export const WORKSPACE_LIST_SEGMENT_SUPPLEMENT_ATTACHMENTS_CHANNEL =
  'workspace:listSegmentSupplementAttachments' as const;
export const WORKSPACE_READ_RECORDING_DRAFT_AUDIO_CHANNEL =
  'workspace:readRecordingDraftAudio' as const;
export const WORKSPACE_APPEND_RECORDING_AUDIO_CHUNK_CHANNEL =
  'workspace:appendRecordingAudioChunk' as const;
export const WORKSPACE_APPEND_SEGMENT_SUPPLEMENT_RECORDING_AUDIO_CHUNK_CHANNEL =
  'workspace:appendSegmentSupplementRecordingAudioChunk' as const;
export const WORKSPACE_CLONE_RECORDING_DRAFT_PREFIX_CHANNEL =
  'workspace:cloneRecordingDraftPrefix' as const;
export const WORKSPACE_FINALIZE_RECORDING_DRAFT_CHANNEL =
  'workspace:finalizeRecordingDraft' as const;
export const WORKSPACE_FINALIZE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL =
  'workspace:finalizeSegmentSupplementRecordingDraft' as const;
export const WORKSPACE_DISCARD_RECORDING_DRAFT_CHANNEL = 'workspace:discardRecordingDraft' as const;
export const WORKSPACE_DISCARD_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL =
  'workspace:discardSegmentSupplementRecordingDraft' as const;
export const WORKSPACE_UPDATE_MEMORY_TITLE_CHANNEL = 'workspace:updateMemoryTitle' as const;
export const WORKSPACE_UPDATE_SEGMENT_TITLE_CHANNEL = 'workspace:updateSegmentTitle' as const;
export const WORKSPACE_UPDATE_SEGMENT_CONTENT_TITLE_CHANNEL =
  'workspace:updateSegmentContentTitle' as const;
export const WORKSPACE_UPDATE_SEGMENT_SUPPLEMENT_TITLE_CHANNEL =
  'workspace:updateSegmentSupplementTitle' as const;
export const WORKSPACE_UPDATE_SEGMENT_CONTENT_TAB_ORDER_CHANNEL =
  'workspace:updateSegmentContentTabOrder' as const;
export const WORKSPACE_UPDATE_WIDGET_TITLE_CHANNEL = 'workspace:updateWidgetTitle' as const;
export const WORKSPACE_UPDATE_WIDGET_TAB_ORDER_CHANNEL = 'workspace:updateWidgetTabOrder' as const;
export const WORKSPACE_SAVE_TRANSCRIPT_CHANNEL = 'workspace:saveTranscript' as const;
export const WORKSPACE_SAVE_SEGMENT_SUPPLEMENT_TRANSCRIPT_CHANNEL =
  'workspace:saveSegmentSupplementTranscript' as const;
export const WORKSPACE_REQUEST_SEGMENT_TRANSCRIPTION_BACKFILL_CHANNEL =
  'workspace:requestSegmentTranscriptionBackfill' as const;
export const WORKSPACE_REQUEST_SEGMENT_SUPPLEMENT_TRANSCRIPTION_BACKFILL_CHANNEL =
  'workspace:requestSegmentSupplementTranscriptionBackfill' as const;
export const WORKSPACE_REQUEST_SEGMENT_SPEECH_SYNTHESIS_CHANNEL =
  'workspace:requestSegmentSpeechSynthesis' as const;
export const WORKSPACE_REQUEST_SEGMENT_SUPPLEMENT_SPEECH_SYNTHESIS_CHANNEL =
  'workspace:requestSegmentSupplementSpeechSynthesis' as const;
export const WORKSPACE_REGENERATE_IMPORTED_SPEECH_SYNTHESIS_CHANNEL =
  'workspace:regenerateImportedSpeechSynthesis' as const;
export const WORKSPACE_BEGIN_MICROPHONE_INTENT_CHANNEL = 'workspace:beginMicrophoneIntent' as const;
export const WORKSPACE_CLEAR_MICROPHONE_INTENT_CHANNEL = 'workspace:clearMicrophoneIntent' as const;
export const WORKSPACE_START_RECORDING_TRANSCRIPTION_CHANNEL =
  'workspace:startRecordingTranscription' as const;
export const WORKSPACE_SEND_RECORDING_TRANSCRIPTION_AUDIO_CHANNEL =
  'workspace:sendRecordingTranscriptionAudio' as const;
export const WORKSPACE_FINISH_RECORDING_TRANSCRIPTION_CHANNEL =
  'workspace:finishRecordingTranscription' as const;
export const WORKSPACE_CLOSE_RECORDING_TRANSCRIPTION_CHANNEL =
  'workspace:closeRecordingTranscription' as const;
export const WORKSPACE_READ_APP_PERMISSION_STATUS_CHANNEL =
  'workspace:readAppPermissionStatus' as const;
export const WORKSPACE_REQUEST_APP_PERMISSION_CHANNEL = 'workspace:requestAppPermission' as const;
export const WORKSPACE_READ_VOICE_TRANSCRIPTION_SETTINGS_CHANNEL =
  'workspace:readVoiceTranscriptionSettings' as const;
export const WORKSPACE_SET_VOICE_TRANSCRIPTION_ENABLED_CHANNEL =
  'workspace:setVoiceTranscriptionEnabled' as const;
export const WORKSPACE_SET_VOICE_SPEECH_SYNTHESIS_SPEAKER_CHANNEL =
  'workspace:setVoiceSpeechSynthesisSpeaker' as const;
export const WORKSPACE_SAVE_VOICE_TRANSCRIPTION_API_KEY_CHANNEL =
  'workspace:saveVoiceTranscriptionApiKey' as const;
export const WORKSPACE_CLEAR_VOICE_TRANSCRIPTION_API_KEY_CHANNEL =
  'workspace:clearVoiceTranscriptionApiKey' as const;
export const WORKSPACE_VALIDATE_VOICE_TRANSCRIPTION_CREDENTIALS_CHANNEL =
  'workspace:validateVoiceTranscriptionCredentials' as const;
export const WORKSPACE_OPEN_VOICE_TRANSCRIPTION_PROVIDER_CONSOLE_CHANNEL =
  'workspace:openVoiceTranscriptionProviderConsole' as const;
export const WORKSPACE_OPEN_MARKDOWN_EXTERNAL_LINK_CHANNEL =
  'workspace:openMarkdownExternalLink' as const;
export const WORKSPACE_RECORDING_TRANSCRIPTION_EVENT_CHANNEL =
  'workspace:recordingTranscriptionEvent' as const;
export const WORKSPACE_FILE_TRUTH_CHANGED_EVENT_CHANNEL = 'workspace:fileTruthChanged' as const;
export const WORKSPACE_REVEAL_MEMORY_SPACE_IN_FINDER_CHANNEL =
  'workspace:revealMemorySpaceInFinder' as const;
export const WORKSPACE_REVEAL_MEMORY_IN_FINDER_CHANNEL = 'workspace:revealMemoryInFinder' as const;
export const WORKSPACE_REVEAL_SEGMENT_IN_FINDER_CHANNEL =
  'workspace:revealSegmentInFinder' as const;
export const WORKSPACE_REVEAL_SEGMENT_SUPPLEMENT_IN_FINDER_CHANNEL =
  'workspace:revealSegmentSupplementInFinder' as const;
export const WORKSPACE_REVEAL_WIDGET_IN_FINDER_CHANNEL = 'workspace:revealWidgetInFinder' as const;
export const WORKSPACE_OPEN_MEMORY_SPACE_AGENTS_FILE_CHANNEL =
  'workspace:openMemorySpaceAgentsFile' as const;
export const WORKSPACE_OPEN_MEMORY_DOCUMENT_CHANNEL = 'workspace:openMemoryDocument' as const;
export const WORKSPACE_OPEN_SEGMENT_DOCUMENT_CHANNEL = 'workspace:openSegmentDocument' as const;
export const WORKSPACE_OPEN_SEGMENT_SUPPLEMENT_DOCUMENT_CHANNEL =
  'workspace:openSegmentSupplementDocument' as const;
export const WORKSPACE_OPEN_WIDGET_DOCUMENT_CHANNEL = 'workspace:openWidgetDocument' as const;
export const WORKSPACE_COPY_MEMORY_SPACE_ABSOLUTE_PATH_CHANNEL =
  'workspace:copyMemorySpaceAbsolutePath' as const;
export const WORKSPACE_COPY_MEMORY_ABSOLUTE_PATH_CHANNEL =
  'workspace:copyMemoryAbsolutePath' as const;
export const WORKSPACE_COPY_SEGMENT_ABSOLUTE_PATH_CHANNEL =
  'workspace:copySegmentAbsolutePath' as const;
export const WORKSPACE_COPY_SEGMENT_SUPPLEMENT_ABSOLUTE_PATH_CHANNEL =
  'workspace:copySegmentSupplementAbsolutePath' as const;
export const WORKSPACE_COPY_WIDGET_ABSOLUTE_PATH_CHANNEL =
  'workspace:copyWidgetAbsolutePath' as const;
export const WORKSPACE_COPY_MEMORY_RELATIVE_PATH_CHANNEL =
  'workspace:copyMemoryRelativePath' as const;
export const WORKSPACE_COPY_SEGMENT_RELATIVE_PATH_CHANNEL =
  'workspace:copySegmentRelativePath' as const;
export const WORKSPACE_COPY_SEGMENT_SUPPLEMENT_RELATIVE_PATH_CHANNEL =
  'workspace:copySegmentSupplementRelativePath' as const;
export const WORKSPACE_COPY_WIDGET_RELATIVE_PATH_CHANNEL =
  'workspace:copyWidgetRelativePath' as const;
export const WORKSPACE_COPY_NEEDS_REVIEW_AGENT_PROMPT_CHANNEL =
  'workspace:copyNeedsReviewAgentPrompt' as const;
export const WORKSPACE_COPY_ARTIFACT_AGENT_PROMPT_CHANNEL =
  'workspace:copyArtifactAgentPrompt' as const;
export const WORKSPACE_COPY_WIDGET_AGENT_PROMPT_CHANNEL =
  'workspace:copyWidgetAgentPrompt' as const;
export const WORKSPACE_READ_ARTIFACT_RUNTIME_STATE_CHANNEL =
  'workspace:readArtifactRuntimeState' as const;
export const WORKSPACE_WRITE_ARTIFACT_RUNTIME_STATE_CHANNEL =
  'workspace:writeArtifactRuntimeState' as const;

export const WORKSPACE_IPC_CHANNELS = [
  WORKSPACE_CHOOSE_DIRECTORY_CHANNEL,
  WORKSPACE_LIST_MEMORY_SPACES_CHANNEL,
  WORKSPACE_INITIALIZE_CHANNEL,
  WORKSPACE_OPEN_CHANNEL,
  WORKSPACE_OPEN_MEMORY_SPACE_CHANNEL,
  WORKSPACE_REMOVE_MEMORY_SPACE_CHANNEL,
  WORKSPACE_UPDATE_MEMORY_SPACE_TITLE_CHANNEL,
  WORKSPACE_CLOSE_CHANNEL,
  WORKSPACE_READ_WORKSPACE_SNAPSHOT_CHANNEL,
  WORKSPACE_CREATE_MEMORY_CHANNEL,
  WORKSPACE_DELETE_MEMORY_CHANNEL,
  WORKSPACE_RESTORE_DELETED_MEMORY_CHANNEL,
  WORKSPACE_RESET_MEMORY_COVER_CHANNEL,
  WORKSPACE_RESTORE_MEMORY_COVER_CHANNEL,
  WORKSPACE_SWITCH_MEMORY_DEFAULT_COVER_CHANNEL,
  WORKSPACE_RESET_SEGMENT_COVER_CHANNEL,
  WORKSPACE_RESTORE_SEGMENT_COVER_CHANNEL,
  WORKSPACE_SWITCH_SEGMENT_DEFAULT_COVER_CHANNEL,
  WORKSPACE_DELETE_SEGMENT_CHANNEL,
  WORKSPACE_RESTORE_DELETED_SEGMENT_CHANNEL,
  WORKSPACE_DELETE_SEGMENT_SUPPLEMENT_CHANNEL,
  WORKSPACE_RESTORE_DELETED_SEGMENT_SUPPLEMENT_CHANNEL,
  WORKSPACE_DELETE_WIDGET_CHANNEL,
  WORKSPACE_RESTORE_DELETED_WIDGET_CHANNEL,
  WORKSPACE_READ_MEMORY_DETAIL_CHANNEL,
  WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_CHANNEL,
  WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_SUPPLEMENT_CHANNEL,
  WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_AUDIO_CHANNEL,
  WORKSPACE_READ_FINALIZED_AUDIO_SEGMENT_SUPPLEMENT_AUDIO_CHANNEL,
  WORKSPACE_READ_EXPRESSION_PLAYBACK_AUDIO_CHANNEL,
  WORKSPACE_CREATE_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_CREATE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_CREATE_NOTE_SEGMENT_DRAFT_CHANNEL,
  WORKSPACE_CREATE_SEGMENT_SUPPLEMENT_NOTE_DRAFT_CHANNEL,
  WORKSPACE_WRITE_NOTE_SEGMENT_DRAFT_BODY_CHANNEL,
  WORKSPACE_WRITE_SEGMENT_SUPPLEMENT_NOTE_DRAFT_BODY_CHANNEL,
  WORKSPACE_FINALIZE_NOTE_SEGMENT_DRAFT_CHANNEL,
  WORKSPACE_FINALIZE_SEGMENT_SUPPLEMENT_NOTE_DRAFT_CHANNEL,
  WORKSPACE_READ_SEGMENT_CONTENT_CHANNEL,
  WORKSPACE_READ_SEGMENT_SPEECH_AUDIO_CHANNEL,
  WORKSPACE_WRITE_SEGMENT_CONTENT_CHANNEL,
  WORKSPACE_READ_SEGMENT_SUPPLEMENT_CONTENT_CHANNEL,
  WORKSPACE_READ_SEGMENT_SUPPLEMENT_SPEECH_AUDIO_CHANNEL,
  WORKSPACE_WRITE_SEGMENT_SUPPLEMENT_CONTENT_CHANNEL,
  WORKSPACE_SAVE_SEGMENT_ATTACHMENT_CHANNEL,
  WORKSPACE_LIST_SEGMENT_ATTACHMENTS_CHANNEL,
  WORKSPACE_SAVE_SEGMENT_SUPPLEMENT_ATTACHMENT_CHANNEL,
  WORKSPACE_LIST_SEGMENT_SUPPLEMENT_ATTACHMENTS_CHANNEL,
  WORKSPACE_READ_RECORDING_DRAFT_AUDIO_CHANNEL,
  WORKSPACE_APPEND_RECORDING_AUDIO_CHUNK_CHANNEL,
  WORKSPACE_APPEND_SEGMENT_SUPPLEMENT_RECORDING_AUDIO_CHUNK_CHANNEL,
  WORKSPACE_CLONE_RECORDING_DRAFT_PREFIX_CHANNEL,
  WORKSPACE_FINALIZE_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_FINALIZE_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_DISCARD_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_DISCARD_SEGMENT_SUPPLEMENT_RECORDING_DRAFT_CHANNEL,
  WORKSPACE_UPDATE_MEMORY_TITLE_CHANNEL,
  WORKSPACE_UPDATE_SEGMENT_TITLE_CHANNEL,
  WORKSPACE_UPDATE_SEGMENT_CONTENT_TITLE_CHANNEL,
  WORKSPACE_UPDATE_SEGMENT_SUPPLEMENT_TITLE_CHANNEL,
  WORKSPACE_UPDATE_SEGMENT_CONTENT_TAB_ORDER_CHANNEL,
  WORKSPACE_UPDATE_WIDGET_TITLE_CHANNEL,
  WORKSPACE_UPDATE_WIDGET_TAB_ORDER_CHANNEL,
  WORKSPACE_SAVE_TRANSCRIPT_CHANNEL,
  WORKSPACE_SAVE_SEGMENT_SUPPLEMENT_TRANSCRIPT_CHANNEL,
  WORKSPACE_REQUEST_SEGMENT_TRANSCRIPTION_BACKFILL_CHANNEL,
  WORKSPACE_REQUEST_SEGMENT_SUPPLEMENT_TRANSCRIPTION_BACKFILL_CHANNEL,
  WORKSPACE_REQUEST_SEGMENT_SPEECH_SYNTHESIS_CHANNEL,
  WORKSPACE_REQUEST_SEGMENT_SUPPLEMENT_SPEECH_SYNTHESIS_CHANNEL,
  WORKSPACE_REGENERATE_IMPORTED_SPEECH_SYNTHESIS_CHANNEL,
  WORKSPACE_BEGIN_MICROPHONE_INTENT_CHANNEL,
  WORKSPACE_CLEAR_MICROPHONE_INTENT_CHANNEL,
  WORKSPACE_START_RECORDING_TRANSCRIPTION_CHANNEL,
  WORKSPACE_SEND_RECORDING_TRANSCRIPTION_AUDIO_CHANNEL,
  WORKSPACE_FINISH_RECORDING_TRANSCRIPTION_CHANNEL,
  WORKSPACE_CLOSE_RECORDING_TRANSCRIPTION_CHANNEL,
  WORKSPACE_READ_APP_PERMISSION_STATUS_CHANNEL,
  WORKSPACE_REQUEST_APP_PERMISSION_CHANNEL,
  WORKSPACE_READ_VOICE_TRANSCRIPTION_SETTINGS_CHANNEL,
  WORKSPACE_SET_VOICE_TRANSCRIPTION_ENABLED_CHANNEL,
  WORKSPACE_SET_VOICE_SPEECH_SYNTHESIS_SPEAKER_CHANNEL,
  WORKSPACE_SAVE_VOICE_TRANSCRIPTION_API_KEY_CHANNEL,
  WORKSPACE_CLEAR_VOICE_TRANSCRIPTION_API_KEY_CHANNEL,
  WORKSPACE_VALIDATE_VOICE_TRANSCRIPTION_CREDENTIALS_CHANNEL,
  WORKSPACE_OPEN_VOICE_TRANSCRIPTION_PROVIDER_CONSOLE_CHANNEL,
  WORKSPACE_OPEN_MARKDOWN_EXTERNAL_LINK_CHANNEL,
  WORKSPACE_READ_SYSTEM_DRAFT_WORKSPACE_CHANNEL,
  WORKSPACE_OPEN_SYSTEM_DRAFT_WORKSPACE_CHANNEL,
  WORKSPACE_READ_RECENT_EXPRESSIONS_CHANNEL,
  WORKSPACE_REVEAL_MEMORY_SPACE_IN_FINDER_CHANNEL,
  WORKSPACE_REVEAL_MEMORY_IN_FINDER_CHANNEL,
  WORKSPACE_REVEAL_SEGMENT_IN_FINDER_CHANNEL,
  WORKSPACE_REVEAL_SEGMENT_SUPPLEMENT_IN_FINDER_CHANNEL,
  WORKSPACE_REVEAL_WIDGET_IN_FINDER_CHANNEL,
  WORKSPACE_OPEN_MEMORY_SPACE_AGENTS_FILE_CHANNEL,
  WORKSPACE_OPEN_MEMORY_DOCUMENT_CHANNEL,
  WORKSPACE_OPEN_SEGMENT_DOCUMENT_CHANNEL,
  WORKSPACE_OPEN_SEGMENT_SUPPLEMENT_DOCUMENT_CHANNEL,
  WORKSPACE_OPEN_WIDGET_DOCUMENT_CHANNEL,
  WORKSPACE_COPY_MEMORY_SPACE_ABSOLUTE_PATH_CHANNEL,
  WORKSPACE_COPY_MEMORY_ABSOLUTE_PATH_CHANNEL,
  WORKSPACE_COPY_SEGMENT_ABSOLUTE_PATH_CHANNEL,
  WORKSPACE_COPY_SEGMENT_SUPPLEMENT_ABSOLUTE_PATH_CHANNEL,
  WORKSPACE_COPY_WIDGET_ABSOLUTE_PATH_CHANNEL,
  WORKSPACE_COPY_MEMORY_RELATIVE_PATH_CHANNEL,
  WORKSPACE_COPY_SEGMENT_RELATIVE_PATH_CHANNEL,
  WORKSPACE_COPY_SEGMENT_SUPPLEMENT_RELATIVE_PATH_CHANNEL,
  WORKSPACE_COPY_WIDGET_RELATIVE_PATH_CHANNEL,
  WORKSPACE_COPY_ARTIFACT_AGENT_PROMPT_CHANNEL,
  WORKSPACE_COPY_WIDGET_AGENT_PROMPT_CHANNEL,
  WORKSPACE_READ_ARTIFACT_RUNTIME_STATE_CHANNEL,
  WORKSPACE_WRITE_ARTIFACT_RUNTIME_STATE_CHANNEL,
  WORKSPACE_COPY_NEEDS_REVIEW_AGENT_PROMPT_CHANNEL,
] as const;

export type WorkspaceIpcChannel = (typeof WORKSPACE_IPC_CHANNELS)[number];

export const WORKSPACE_RENDERER_EVENT_CHANNELS = [
  WORKSPACE_RECORDING_TRANSCRIPTION_EVENT_CHANNEL,
  WORKSPACE_FILE_TRUTH_CHANGED_EVENT_CHANNEL,
] as const;

export type WorkspaceRendererEventChannel = (typeof WORKSPACE_RENDERER_EVENT_CHANNELS)[number];
